/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include "schedular.h"
#include "string.h"
Task_t Task1;
uint32_t g_task1;

Task_t Task2;
uint32_t g_task2;

uint32_t g_idleTask;

Mutex_t g_Mutex1;

void IdleHook(void)
{
	g_idleTask^=1;
}

void Task1_entry()
{
	while(1)
	{
		g_task1^=1;

		//Jarvis_PrioritySet(&Task2, Jarvis_PriorityGet(&Task1)-1);

		Jarvis_AcquireMutex(&g_Mutex1, &Task1);

		Jarvis_waitTicks(&Task1, 2);

		Jarvis_ReleaseMutex(&g_Mutex1, &Task1);


	}
}

void Task2_entry()
{
	while(1)
	{
		g_task2^=1;

		Jarvis_AcquireMutex(&g_Mutex1, &Task2);
		//Jarvis_PrioritySet(&Task2, Jarvis_PriorityGet(&Task2)+2);
		//Jarvis_waitTicks(&Task2, 1);

		Jarvis_ReleaseMutex(&g_Mutex1, &Task2);
	}
}

int main(void)
{


	HW_init();


	Task1.priority=2;

	Task1.p_task_enrty=Task1_entry;

	Task1.stack_size=200;

	strcpy(Task1.TaskName,"Task 1");

	Task2.priority=3;

	Task2.p_task_enrty=Task2_entry;

	Task2.stack_size=200;

	strcpy(Task2.TaskName,"Task 2");




	Jarvis_init();

	Jarvis_CreateTask(&Task1);

	Jarvis_CreateTask(&Task2);

	Jarvis_ActivateTask(&Task1);

	Jarvis_ActivateTask(&Task2);

	Jarvis_StartSchedular();

    /* Loop forever */
	for(;;);
}
